// Version labels follow Eledger's scheme: first entry is v1.0, each
// subsequent entry is +0.1, up to a max of x.10 — the entry after any x.10
// rolls to (x+1).0. One entry per release (not per commit — a release here
// can bundle several commits). Oldest first below (rendered newest-first in
// the UI by the shared @brand/Changelog component).
export const CHANGELOG = [
  {
    v: "v1.0", date: "March 2026",
    title: "PDF export removed",
    notes: [
      "Excel export remains; PDF will be reintroduced with a print stylesheet.",
    ],
  },
  {
    v: "v1.1", date: "April 2026",
    title: "Onboarding stability",
    notes: [
      "Auth race-condition fix — no more reload-to-continue after sign-up.",
      "Error messages now clear when navigating between onboarding screens.",
    ],
  },
  {
    v: "v1.2", date: "May 2026",
    title: "Carry-forward fix · refresh polish",
    notes: [
      "Carry-forward hours over 9:59 no longer zero out on save.",
      "Refresh button has minimum 800ms spinner + proper error state.",
      "Profile settings no longer overwritten by stale legacy profile document on load.",
      "Footer version corrected (was showing v5.5).",
    ],
  },
  {
    v: "v1.3", date: "May 2026",
    title: "ClaudeBorne brand rollout",
    notes: [
      "Full visual rebuild — new logo, typography, surfaces, and gradient accents.",
      "Appearance settings curated to a brand-safe palette (5 accent presets).",
      "Day/Night column headers now carry sun/moon glyphs for color-blind safety.",
      "Save status chip in page header — 5 states: auto-save off / unsaved / saving / saved / error (with retry).",
      "Dirty state: chip pulses amber when there are unsaved changes.",
      "PWA manifest wired — app is installable from supported browsers.",
      "window.confirm() replaced with branded confirmation modal.",
      "Remarks, Regulatory reference, Save error modals migrated to CB tokens — work in light mode.",
      "Save error modal now has a Retry button; dismiss returns to dirty (not idle).",
      "Annual overview table: ☀ DAY / ☾ NIGHT column group headers added.",
      "Hardcoded dark-only hex in cell editor, FTL cards, and save button replaced with CB tokens.",
    ],
  },
  {
    v: "v1.4", date: "May 2026",
    title: "Settings overhaul · save chip fix",
    notes: [
      "Profile tab: all data fields standardised to identical width.",
      "Accent palette expanded from 5 to 10 presets: added Emerald, Rose, Cyan, Gold, Coral.",
      "Accent swatches now span full modal width.",
      "Table density split into two independent controls — Row (Compact / Default / Relaxed) and Column (Narrow / Default / Wide).",
      "Save chip: auto-save off + no prior save shows AUTO-SAVE OFF · NOT YET SAVED.",
      "Save chip: after manual save with auto-save off, shows SAVED · timestamp persistently.",
      "SAVE NOW button turns amber when auto-save is disabled.",
      "Per-tab reset to default added to settings footer — Appearance and Preferences tabs only.",
      "Miscellaneous tab reinstated with support action cards (How-to Guide, Report a Bug, Suggest a Feature) and changelog.",
      "Tab bar: full-width border line added beneath tabs.",
      "FTL fix: day/night method setting now correctly applied to cumulative FTL calculations.",
      "Export/Import: native alert() dialogs replaced with inline branded status messages.",
    ],
  },
  {
    v: "v1.5", date: "May 2026",
    title: "Column visibility · UX polish · live preview",
    notes: [
      "Column visibility: toggle any logbook column on/off from Settings → Appearance.",
      "DAY and NIGHT groups each enforce a minimum of 1 visible column.",
      "Hidden columns show a narrow rotated stub in the table header — click stub to restore.",
      "Appearance tab: all changes now apply as a live preview before saving.",
      "Changelog: current version always visible; older versions collapsed behind a toggle.",
      "Support: Report a Bug and Suggest a Feature merged into a single banner.",
      "Settings modal stays open after Save — manual close only.",
      "Light mode now applies correctly inside the Settings modal.",
      "Font family and size changes now apply inside Settings modal.",
      "Manual save no longer incorrectly triggers 'AUTOSAVE FAILED' error.",
      "Limits & Recency — all status banners and info text left-aligned.",
      "Remarks modal — REMARKS title left-aligned.",
      "Footer updated to CAD 1901 · MCAR 2016 Part 69 & Part 74.",
      "FIX: Firebase token refresh (every ~1 hr) no longer reloads Firestore and wipes unsaved local data.",
      "FIX: Export now includes manually-entered flights (day-number date format was silently excluded).",
      "FIX: Import modal now shows an explicit error if the cloud save fails instead of silently showing success.",
      "FIX: Re-importing Excel no longer creates duplicate rows for manually-entered flights.",
      "FIX: Browser close warning now fires when last save errored (not just when dirty).",
      "FIX: loadData no longer calls setData({}) when Firestore logbookData is an empty map — prevents wiping unsaved local data.",
      "FIX: Dates entered as DD/MM or DD/MM/YYYY are normalised to day-number on input — prevents silent export omission.",
      "FIX: Export now includes rows with DD/MM format dates (e.g. '15/05') in addition to day-number and DD/MM/YYYY formats.",
      "FIX: SAVE NOW and auto-save now always use the live React state — stale ref could previously cause logbookData to be wiped from Firestore.",
      "Column visibility revamped — DAY, NIGHT, and TOTAL columns are now always visible; only TYPE, MARKINGS, CAPTAIN, HOC, PF, DEP, ARR, STD, STA are toggleable.",
      "FIX: Hiding columns in Settings no longer resets on the 3rd toggle — auto-save was overwriting the Settings draft mid-edit via Firestore onSnapshot.",
      "FIX: Settings Save button no longer disappears off-screen on small screens — footer now always stays anchored to the bottom of the modal.",
      "FIX: Hiding a column no longer shifts all subsequent data cells left — hidden columns now render a narrow stub td to keep header and data rows aligned.",
      "FIX: Hiding a solo column (CAPTAIN, HOC, PF, STD, STA, TOTAL) no longer shifts sub-header row — stub now correctly spans both header rows.",
      "Real-time multi-device sync: app now stays live with Firestore — changes saved on any device appear on all other open devices within seconds.",
      "Sync conflict protection: if another device saves while you have unsaved local changes, a banner prompts you to Save Mine or Discard & Sync.",
    ],
  },
  {
    v: "v1.6", date: "May 2026",
    title: "In-app feedback · bug reports · feature requests",
    notes: [
      "NEW: In-app feedback system — Report a Bug and Suggest a Feature now open a native modal instead of an external link.",
      "Feedback submissions are stored in Firestore and include user email, app version, and timestamp — no extra login required.",
    ],
  },
  {
    v: "v1.7", date: "May 2026",
    title: "Local-first architecture · PWA · offline support · manual sync",
    notes: [
      "NEW: Local-first architecture — all data now saves to device storage instantly. No network required to save.",
      "NEW: Manual SYNC button — push your logbook to the cloud and pull to other devices on demand.",
      "NEW: Sync conflict modal — when another device has newer cloud data, choose Keep Local or Keep Cloud.",
      "NEW: Offline indicator — toolbar shows OFFLINE chip when internet is unavailable; SYNC button disabled.",
      "NEW: PWA support — install C·B eLogBook on iOS and Android home screens. App loads and works fully offline after first install.",
      "NEW: Auto-update prompt — notifies you when a new version is available, updates safely after saves complete.",
      "IMP: Save-on-change — data writes to device storage on every edit. Auto-save interval setting removed.",
      "IMP: Existing users migrated automatically on first load — your Firestore data is pulled to local storage seamlessly.",
      "IMP: Last synced timestamp now persists across sessions — toolbar always shows when data was last pushed to cloud, even offline.",
      "IMP: Cloud-newer check now runs on reconnect and when app returns to foreground — banner appears automatically if another device has synced.",
      "IMP: Sync no longer shows conflict modal when local data is unchanged — silently pulls cloud data if no local edits exist since last sync.",
      "IMP: Save chip reworked — SAVING... (yellow, animated) transitions to SAVED TO LOCAL STORAGE (green) after editing pauses. SAVE NOW button removed.",
      "FIX: Last-synced timestamp was incorrectly updated on every local save — conflict detection now works correctly across multiple devices.",
      "FIX: Excel export Summary and Flights tabs showed 0:00:00 for all day/night/total columns — flight times are now computed correctly during export.",
    ],
  },
  {
    v: "v1.8", date: "May 2026",
    title: "How-To Guide · UI polish · export fix",
    notes: [
      "NEW: In-app How-To Guide — 8 sections covering getting started, installing the app, logging flights, day/night calculation, carry forward hours, syncing, exporting, and settings.",
      "IMP: Toolbar icons enlarged and colour updated to mint for consistency.",
      "IMP: Export/Import icon stroke weight corrected to match other toolbar icons.",
      "IMP: How-To Guide and Send Feedback banners now equal size in Settings.",
      "IMP: Landing page logo updated to C Mark.",
      "FIX: Excel export Summary and Flights tabs showed 0:00:00 for all day/night/total columns — flight times are now computed correctly during export.",
    ],
  },
  {
    v: "v1.9", date: "May 2026",
    title: "Google sign-in reliability (desktop)",
    notes: [
      "FIX: Google sign-in on desktop browsers with ad blockers / popup blockers now shows a clear error message instead of silently failing.",
      "NEW: Auto-recovery safety net — if Google sign-in succeeds but the UI gets stuck on the login screen, the app now auto-reloads to recover (one-shot per session, no manual refresh needed).",
      "IMP: Sign-in attempt now times out after 20 seconds with an actionable error message — no more permanently stuck \"LOGGING IN...\" button.",
    ],
  },
  {
    v: "v1.10", date: "May 2026",
    title: "Hotfix — revert PWA redirect auth",
    notes: [
      "FIX: Revert v6.6 PWA redirect-based Google sign-in — installed PWAs were landing on the welcome page after Google sign-in with no auth. Reverted to popup-based flow (same as v6.5 behaviour on PWA).",
      "IMP: Desktop Google sign-in improvements from v6.6 retained — auto-recovery reload, 20s timeout, ad-blocker error messages all still active.",
      "PWA Google sign-in fix is in progress via a different approach (Google Identity Services); v6.6.1 restores PWA users to v6.5 behaviour in the meantime.",
    ],
  },
  {
    v: "v2.0", date: "May 2026",
    title: "Column hide actually hides · gear badge · toast reminder",
    notes: [
      "FIX: Hiding a column now removes it entirely from the table — previously it was reduced to a 13-pixel stub that still took horizontal space, defeating the purpose of hiding.",
      "FIX: AIRCRAFT and SECTORS group headers now disappear when both their sub-columns are hidden — previously the group label stayed visible above empty stubs.",
      "NEW: Gear icon carries a count badge whenever columns are hidden — at a glance you can see how many are tucked away.",
      "NEW: Toast strip above the table briefly appears when you hide a column (or on page load if any are hidden) — auto-fades after 5 seconds, or click ✕ to dismiss.",
      "NEW: Clicking the badge or toast opens Settings directly on the Appearance tab to manage column visibility.",
    ],
  },
  {
    v: "v2.1", date: "May 2026",
    title: "Hotfix — account deletion order",
    notes: [
      "FIX: Account deletion now removes Firestore data before invalidating the auth user. Previous order could leave logbook data orphaned in the cloud if Firestore was slow to acknowledge the auth-token revocation between deleteUser() and the subsequent deleteDoc() calls.",
    ],
  },
  {
    v: "v2.2", date: "June 2026",
    title: "Column visibility expansion · Settings polish · regulatory popups",
    notes: [
      "NEW: Every logbook column is now toggleable — including DAY P1 / P1 U/S / P2, NIGHT P1 / P1 U/S / P2, and TOTAL. Previously these seven were forced-visible.",
      "NEW: The Appearance tab in Settings now shows the same mint count badge that appears on the toolbar gear icon, so you can spot the hidden-columns control without opening the tab first.",
      "IMP: Limits & Recency regulatory reference popups (all 7) now have consistent left text alignment across title, body, and note sections.",
      "IMP: Limits & Recency disclaimer trimmed from ~95 words to ~30 — keeps the reference-only framing and user-responsibility note; regulation references corrected to CAD 1901 and MCAR 2016 Part 69 & Part 74.",
      "IMP: Settings → Appearance → Column visibility hint updated — \"click a stub in the table header to restore\" was stale text from before v6.7 removed stubs.",
    ],
  },
  {
    v: "v2.3", date: "June 2026",
    title: "Route-based day/night calculation",
    notes: [
      "NEW: The Sunrise/Sunset day/night method has been upgraded to a route-integrated calculation, renamed Route (sun). Night is now counted whenever the sun is below civil twilight (−6°), computed minute by minute along the actual great-circle route between departure and arrival airports.",
      "IMP: Day/night now accounts for the aircraft moving between time zones. An eastbound flight landing into the sunrise correctly logs its final stretch as day — previously the whole sector was anchored to the departure airport (or a fixed UTC band) and could be logged as 100% night.",
      "IMP: Both departure AND arrival airport codes now drive the calculation. If either is missing from the coordinates database, that sector falls back to the Fixed bands method, and the unrecognised code is highlighted in the table.",
      "IMP: −6° civil twilight matches the ICAO/EASA definition of night and is the physical basis of the CAD-6 sunset+20 / sunrise−20 heuristic the previous method approximated.",
    ],
  },
  {
    v: "v2.4", date: "June 2026",
    title: "Google sign-in rebuilt with Google Identity Services",
    notes: [
      "NEW: Google sign-in now uses Google Identity Services (GIS). On installed PWAs (iPad / Android home-screen app), Google sign-in works reliably — no more getting stuck on the login screen or having to force-quit and reopen.",
      "IMP: Desktop Google sign-in is also more robust against ad blockers and popup blockers, since GIS doesn't rely on a popup handshake.",
      "IMP: If the Google script is ever blocked, the button automatically falls back to the previous popup method, and email/password sign-in is always available.",
      "Email/password sign-in is unchanged.",
    ],
  },
  {
    v: "v2.5", date: "June 2026",
    title: "Google account deletion works on PWA",
    notes: [
      "FIX: Deleting a Google account from an installed PWA now works. When Google asks you to re-confirm your identity, the app uses Google Identity Services (the same reliable method as sign-in) instead of a popup — so it no longer gets stuck on iPad / Android home-screen apps.",
      "IMP: If the Google script is blocked, account deletion falls back to the previous popup method on desktop.",
      "IMP: Clearer message if you pick the wrong Google account during deletion.",
      "Email/password account deletion is unchanged.",
    ],
  },
  {
    v: "v2.6", date: "June 2026",
    title: "Account deletion polish",
    notes: [
      "NEW: After deleting your account you now see a clear confirmation — \"✓ ACCOUNT DELETED\" — instead of the generic signed-out screen.",
      "NEW: Right-to-erasure — any feedback you submitted is anonymised (your email and ID removed) when you delete your account.",
      "IMP: If account deletion is interrupted (app closed mid-way, lost connection), it now resumes and finishes cleanly the next time you open the app, so nothing is left half-deleted.",
    ],
  },
  {
    v: "v2.7", date: "June 2026",
    title: "Hotfix — HOC warning banner overflow",
    notes: [
      "FIX: The \"HOLDER OPERATING CAPACITY required\" banner now spans exactly the DAY, NIGHT and TOTAL columns instead of overflowing past the table into the action buttons. It was anchoring on the TOTAL column by mistake.",
    ],
  },
  {
    v: "v2.8", date: "June 2026",
    title: "Hotfix — sign-up & sign-in flow",
    notes: [
      "FIX: New Google sign-ups now go through onboarding instead of dropping straight into the logbook.",
      "FIX: Email sign-up no longer refreshes back to the landing page while waiting for email verification.",
      "FIX: After verifying your email, logging in no longer gets stuck on \"Setting up your logbook\" — verified accounts now load correctly.",
      "NEW: Forgot password — the login screen's FORGOT PASSWORD? link now sends a reset email.",
    ],
  },
  {
    v: "v2.9", date: "June 2026",
    title: "Sign-in & account deletion reliability",
    notes: [
      "FIX: Typing your email or password on the login and forgot-password screens no longer gets wiped mid-entry. The screens were quietly resetting on each redraw.",
      "FIX: Logging in after a password reset no longer gets stuck on \"Setting up your logbook\" — the screen now always clears.",
      "IMP: Deleting your account now confirms your identity before anything is removed. If you cancel at the password / Google prompt, nothing is deleted — no more half-removed accounts.",
      "NEW: The \"resend verification email\" link on the verify-email screen now works — it re-sends the link, with a 30-second cooldown to avoid duplicates.",
      "FIX: New versions now prompt automatically. The app re-checks for updates every 30 minutes and whenever you reopen it, instead of only when you tapped \"check for updates\" manually.",
      "NEW: Export All — a new button in the Export window exports every flight in your logbook to Excel without having to set a date range.",
      "FIX: After clicking your verification link, the app now detects it immediately instead of staying stuck on the \"check your email\" screen until you manually refreshed.",
      "FIX: If account deletion was interrupted and couldn't fully complete on the next app load, you now see a clear message telling you to finish via Settings → Delete Account instead of a silent failure.",
      "FIX: Selecting a non-Excel file in the Import screen no longer loads the entire file into memory before rejecting it.",
      "FIX: The \"New version available\" update banner no longer throws if the service worker updater isn't ready yet.",
      "FIX: If you log in twice in quick succession as the same account, the loading overlay can no longer get stuck from a stale timer.",
      "FIX: Opening the app no longer briefly flashes the pilot-profile setup screen before landing on the logbook.",
      "IMP: Export window — the Export and Export All buttons are now the same width with a consistent gap between them.",
      "IMP: Settings → Misc tab no longer shows a Save / Cancel button bar — no settings on that tab need saving.",
      "IMP: Day/Night method renamed from \"Route (sun)\" to \"Dynamic\"; description shortened.",
      "IMP: On mobile, section heading hints are hidden so titles never wrap to two lines.",
      "NEW: Empty rows from the previous month are automatically trimmed at midnight when the calendar month changes.",
    ],
  },
  {
    v: "v2.10", date: "June 2026",
    title: "Adaptive logbook width",
    notes: [
      "IMP: The logbook now sizes itself to fit all columns exactly on any desktop screen — no more horizontal scrolling. The app measures the table's actual rendered width after layout and sets its own container to match.",
      "IMP: Empty space on either side of the app adjusts automatically — wider screens get more margin, narrower screens get less. Column widths never change unless you pick Narrow / Default / Wide in Settings.",
      "FIX: Added HTTP security headers (CSP, X-Frame-Options, X-Content-Type-Options) to prevent clickjacking and MIME sniffing.",
      "IMP: You can now delete any row — including unused empty ones. The Rows Per Page setting is a visual default for new months only, not a hard minimum.",
      "IMP: Remarks moved off a per-row button onto the row number itself — tap any row number to open its remarks / autoland window. A coloured dot beside the number shows its state (gold = remarks, purple = autoland, green = both). Frees up a column and works the same on phone, tablet and desktop.",
      "FIX: The brand logo and month/year headings now always render in the correct font. They previously loaded from Google Fonts, so ad blockers and tracker-blocking browsers (Brave, uBlock Origin, Firefox strict mode) could silently block the request and fall back to a generic system font. All fonts are now bundled with the app itself.",
    ],
  },
  {
    v: "v3.0", date: "June 2026",
    title: "Brand banner & self-hosted fonts",
    notes: [
      "NEW: New topbar brand banner — outlined 'C' in Tourney 900, gradient CLAUDEBORNE wordmark, PILOT eLOGBOOK subtitle with corner chevrons framing the brand section.",
      "IMP: All web fonts are now self-hosted (public/fonts/). Google Fonts CDN is no longer loaded — fonts are served directly from ClaudeBorne's own origin, improving privacy, reliability, and load performance.",
      "IMP: Content Security Policy tightened — fonts.googleapis.com and fonts.gstatic.com removed from the allowlist now that nothing depends on them.",
      "FIX: Tab bar on mobile — selecting the Logbook tab no longer wraps all tabs to two lines. The selected-tab bottom border is now also correctly hidden on all tabs when selected.",
    ],
  },
  {
    v: "v3.1", date: "June 2026",
    title: "Security & reliability hardening",
    notes: [
      "FIX: Choosing \"Keep Local Data\" after a cloud sync conflict no longer triggers a second conflict popup — local data is now pushed directly to the cloud in a single step.",
      "FIX: Closing the app or signing out while a confirmation dialog was open could leave it stuck on screen. Now dismissed cleanly.",
      "NEW: A warning banner now appears when the app cannot save data to your device (e.g. private/incognito browsing). Switch to a normal browser tab to restore device saving.",
      "IMP: Import now rejects files over 10 MB immediately with a clear error, instead of attempting to load them.",
      "IMP: Excel import/export library replaced with ExcelJS — actively maintained with no known security issues.",
      "IMP: The 60-second cooldown between feedback submissions now persists across page refreshes and browser tabs.",
      "IMP: Pilot notes and remarks are now sanitised before display, preventing any malformed content from affecting the page.",
      "FIX: Corrected a crash-risk in the auth provider check that could occur on certain sign-in states.",
      "DEP: Removed unused jsPDF and firebase-admin packages from the app bundle.",
      "IMP: Airport coordinate data now loads in a separate browser cache chunk — future updates download less data.",
    ],
  },
  {
    v: "v3.2", date: "June 2026",
    title: "Custom icon set replaces emoji",
    notes: [
      "NEW: Landing screen Log In / Sign Up Free tiles, the email/verification screens, and the signed-out screen now use custom brand-gradient icons (a paper plane, a boarding pass, an envelope, and a door) instead of emoji.",
      "NEW: The Logbook, Flight Summary, and Limits & Recency tab icons are now custom illustrations (a stamped page, a climb-profile chart, and a cockpit limits gauge) instead of emoji.",
      "IMP: All replaced icons render as inline SVG, so they look identical across every browser and OS instead of varying by the platform's emoji font.",
    ],
  },
  {
    v: "v3.3", date: "June 2026",
    title: "Animated launch splash",
    notes: [
      "NEW: A short animated splash screen now plays on app launch — the C mark fades in, the chamfered double-line frame draws on around it, then the CLAUDEBORNE wordmark fades in, before settling into the app.",
    ],
  },
  {
    v: "v3.4", date: "June 2026",
    title: "Route map",
    notes: [
      "NEW: Route Map — plot every sector flown in a chosen date range on a world map, with a colour-graded great-circle line (magenta → yellow) for each route and PNG export to share where you've flown. Open it from the toolbar or the Flight Summary tab.",
      "NEW: Choose your basemap — a watermark-free vector world outline (default), CARTO Dark, Esri Satellite, or Stadia Dark.",
      "IMP: A route flown more than once in the selected period is drawn once, not duplicated per sector.",
      "IMP: Removed the duplicate \"View Route Map\" button from the Flight Summary tab — open the route map from the toolbar icon.",
      "IMP: Route map PNG/JPG export now renders at 4x resolution (previously 2x) for a sharper image.",
      "FIX: Stadia Dark basemap now loads correctly — no API key required.",
      "IMP: Removed the Logbook tab's info button — its data-entry tips now live in the How-To Guide (Settings → Misc → How-To Guide → The Logbook).",
    ],
  },
  {
    v: "v3.5", date: "July 2026",
    title: "Day/night accuracy, sync scaling, and fixes",
    notes: [
      "FIX: Takeoff/landing recency (Dynamic day/night mode) now checks the actual sun position at the moment of departure/arrival, instead of which had more total daylight across the whole flight — these could previously disagree on long-haul sectors.",
      "FIX: Entering a day that doesn't exist in the selected month (e.g. \"31\" in February) is now rejected instead of silently accepted.",
      "NEW: A non-blocking warning now appears when two flights on the same date have overlapping STD–STA times, flagging a possible duty conflict.",
      "IMP: Onboarding now asks for your airline and home base up front (previously \"organization\" vs \"airline\" were inconsistently labelled across screens).",
      "IMP: Flight-time totals (monthly totals row, annual summary) now compute faster, with no change to the numbers themselves.",
      "IMP: Flight log data now syncs to the cloud as one document per year instead of one document for your whole career, removing a long-term storage ceiling. Existing data migrates automatically and non-destructively the next time you sync or sign in on a new device.",
      "FIX: Duty-hour totals (7/14/28-day) no longer overcount multi-sector duty days — the pre/post-flight buffer now applies once per duty day instead of once per sector.",
      "IMP: Removed an unused internal \"sectors\" data field that had no on-screen input and was never populated — no functional change.",
    ],
  },
  {
    v: "v3.6", date: "July 2026",
    title: "Multi-sector auto-fill",
    notes: [
      "NEW: When you add a row with the same date as the row above (multi-sector duty day), aircraft type, markings, and captain auto-fill from the previous row — only into empty fields, never overwriting what you've already typed.",
      "IMP: Route Map now defaults to the watermark-free VECTOR basemap (previously CARTO Dark), since it's the only basemap that renders fully offline.",
    ],
  },
  {
    v: "v3.7", date: "July 2026",
    title: "Auto-hide empty flight-time columns",
    notes: [
      "NEW: DAY and NIGHT columns (P1, P1 U/S, P2) that are completely empty for a month now collapse into a slim marker instead of a row of dashes — tap it to reveal the column again. Only ever applies to past, closed-out months, never the one you're actively logging, and a column with even one real entry is never touched. Toggle it off in Settings → Appearance if you'd rather always see every column.",
      "DEP: Removed the manual per-column \"hide column\" setting from Settings → Appearance — superseded by the automatic behaviour above for DAY/NIGHT columns; every other column is now simply always shown.",
      "NEW: Added a \"Go to today\" button next to the period selector on the Logbook tab — jumps straight back to the current month. Greys out when you're already viewing it.",
      "FIX: Opening the app on a device that already has locally cached data no longer skips checking the cloud entirely — it now silently pulls newer cloud data in the background, or opens the sync conflict dialog if this device also has unsynced local changes. Previously this only happened when manually tapping Sync.",
    ],
  },
  {
    v: "v3.8", date: "August 2026",
    title: "Autoland panel redesign",
    notes: [
      "NEW: Row-number tap now expands an inline panel instead of a popup — no dimmed backdrop, accordion-style (one row open at a time).",
      "NEW: \"Duplicate previous row\" action on empty rows — copies date, type, registration, captain, and cap role from the row above, and sets departure to its arrival. Never copies times, remarks, or autoland, so recency tracking is never affected.",
      "IMP: Remarks and the AUTOLAND checkbox now commit immediately — no more separate \"Save remarks\" button.",
      "IMP: Delete moved from a bare \"✕\" column into the panel as a labelled button, with a two-step confirm for rows that have data.",
      "NEW: Settings → Appearance → toggle to animate the row panel opening and closing (on by default).",
      "FIX: Add-sector button now sits inside the MONTHLY TOTALS row on desktop, and floats over the table on touch devices or a narrow window — visible without scrolling either way, instead of buried off to the right.",
    ],
  },
  {
    v: "v3.9", date: "August 2026",
    title: "Duty Log Link",
    notes: [
      "NEW: Link your Duty Log app via a sync code (Settings → Preferences → Duty Log Link) — matches sectors by date + departure/arrival and shows crew (name + position) alongside Remarks in the sector panel.",
      "NEW: Duty Log's sector remark auto-merges into your own Remarks — fills it if blank, appends with a \"[Duty Log]\" tag if you'd already written something. Never overwrites, never duplicates on re-sync.",
    ],
  },
  {
    v: "v3.10", date: "September 2026", current: true,
    title: "Logbook search",
    notes: [
      "NEW: Logbook search — tap the search icon to find any flight by airport, aircraft markings, captain, Duty Log crew, or remarks, across every logged month at once. Selecting a result jumps to that month and briefly highlights the row.",
      "NEW: Prev / next month arrows added beside the period selector — step through months without opening the dropdowns.",
      "FIX: Duty Log crew, sector remark, and duty notes no longer disappear when you go offline — the last successful sync is now cached on-device and restored automatically.",
      "IMP: Page header and tab bar reworked for phone screens — content no longer gets clipped or drags the whole page sideways when scrolling the table; the period picker and save-status chip are repositioned for a tidier phone layout.",
      "IMP: Tabs restyled as bordered dividers — each tab is fully boxed, and the active tab visually fuses into the panel below it.",
    ],
  },
];
